// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHffycTSqmRCvSawNjhavE8nqzC0_LHHc',
    appId: '1:39730604874:web:d8a5674c7cebe374316fb3',
    messagingSenderId: '39730604874',
    projectId: 'profitpulse-c8839',
    authDomain: 'profitpulse-c8839.firebaseapp.com',
    storageBucket: 'profitpulse-c8839.appspot.com',
    measurementId: 'G-3BPQ2BPGR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhzp90ALG8GjXMxoLBlfU6iGDcHV5toF0',
    appId: '1:39730604874:android:1e16999d7ea35e2e316fb3',
    messagingSenderId: '39730604874',
    projectId: 'profitpulse-c8839',
    storageBucket: 'profitpulse-c8839.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUNenOFu5q-uNFpgxYRP5mdOvGwPdltU',
    appId: '1:39730604874:ios:a627b204dcfd8478316fb3',
    messagingSenderId: '39730604874',
    projectId: 'profitpulse-c8839',
    storageBucket: 'profitpulse-c8839.appspot.com',
    iosBundleId: 'com.example.profitpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiUNenOFu5q-uNFpgxYRP5mdOvGwPdltU',
    appId: '1:39730604874:ios:a627b204dcfd8478316fb3',
    messagingSenderId: '39730604874',
    projectId: 'profitpulse-c8839',
    storageBucket: 'profitpulse-c8839.appspot.com',
    iosBundleId: 'com.example.profitpulse',
  );
}
